\documentclass[10pt,reqno,final]{amsart}
%\VignetteIndexEntry{Introduction to pomp}
\usepackage{times}
\usepackage[utf8]{inputenc}
\usepackage[pdftex]{graphicx}
\usepackage[round]{natbib}
\usepackage{paralist}
\usepackage{float}

\setlength{\textwidth}{6.25in}
\setlength{\textheight}{8.75in}
\setlength{\evensidemargin}{0in}
\setlength{\oddsidemargin}{0in}
\setlength{\topmargin}{-0.35in}
\setlength{\parskip}{0.1in}  
\setlength{\parindent}{0.0in}  
\setcounter{secnumdepth}{1}
\setcounter{tocdepth}{1}

\floatstyle{ruled}
\newfloat{textbox}{t}{tbx}
\floatname{textbox}{Box}

\newcommand{\code}[1]{\texttt{#1}}
\newcommand{\pkg}[1]{\textsf{#1}}
\newcommand{\R}{\textsf{R}}
\newcommand{\expect}[1]{\mathbb{E}\left[#1\right]}

\title[Introduction to coalgem]{Introduction to colgem:\\ COalescent Likelihood for Generalized Epidemiologic models}

\author[Volz]{Erik M. Volz}
\author[Romero]{Ethan O. Romero-Severson}
\author[]{Not sure who all is on this list or the order}

\address{
  E.M. Volz,\\
  Department of Public Health,\\ 
  Imperial College
}

\email{eriks email} 

\urladdr{http://??????}

\date{\today }%, \pkg{pomp}~version~\Sexpr{packageDescription("pomp",fields="Version")}}

\SweaveOpts{echo=T,results=verbatim,print=F,eps=F,pdf=T,keep.source=T,resolution=100}

\begin{document}
\SweaveOpts{concordance=TRUE}

\thispagestyle{empty}

\maketitle

\tableofcontents

<<set-opts,echo=F,results=hide>>=
  glop <- options(keep.source=TRUE,width=60,continue=" ",prompt=" ")
  pdf.options(useDingbats=FALSE)
  set.seed(5384959)
@ 

\section{What \pkg{colgem} does}
\pkg{colgem} is intended to provide a simple set of methods for calculating the likelihood of a coalescent geneology under the assumption of user-defined epidemiologic model of arbitrary complexity.
Typically the coalescent geneology not directly observed unobserved but rather estimated from a set of sequence data using relaxed clock phylogentic methods [XXX-beast]

\section{Coalescent likelihood for an unstructred epidemiologic model}
An unstrucutred epimiologic model is any model where there is only one infected class. 

\section{Coalescent likelihood for a structred epidemiologic model}

\end{document}

<<restore-opts,echo=F,results=hide>>=
options(glop)
@ 