#~ NOTE JULY 16 '14, currently broken
#~ HIV model, random sample 200 at 20 years
#~ simulated tree using MASTER 1.4.1 http://tgvaughan.github.io/MASTER/
#~ simulation used Gillespie discrete event methods; see HIVModel.xml 
#~ post-process tree using phytools- see read_master.R
#~ see HIVModel.xml for model specification
#~ We will fit a deterministic model to the simulated data, providing approximate MLEs of beta0 and beta1

#~ Model reaction equations: 
#~ rate( S -> I0 )  = beta0*S*I0 + beta1*S*I1
#~ rate( I0 -> I1) = gamma0 * I0
#~ rate( I1 -> 0) = gamma1 * I1
#~ rate( 0-> S) = b * S

#~ true parameter values
S0 <- 999; sampleTime <- 20; beta0 <- .001; beta1 <- .0001; gamma0 <- 1; gamma1 <- 0.1111; b <- .01

require(rcolgem)
require(deSolve)
require(ape)
require(rjson)
require(stats4)


#~ load the simulation data generated by MASTER
hivSimulationData <- fromJSON(file= system.file('extdata/HIVModel.json', package = "rcolgem") )

#~ load the tree into an ape::phylo
tree <- read.tree( system.file('extdata/HIVModel.nwk', package = "rcolgem") )

#~ load the sample dates and sample times
sampleTimes <- rep(sampleTime, length(tree$tip.label))
#~ the tip.labels are annotated with the state of the patient at time of sampling
calcStateFromName <-function(tl){
	lentl <- nchar(tl)
	tailstr <- substr(tl, lentl-1, lentl)
	if (tailstr == 'I0' ){ return(c(1,0)) }
	return(c(0,1))
}
sampleStates <- t( sapply(tree$tip.label, calcStateFromName) )

#~ make a dated tree
bdt <- binaryDatedTree(tree, sampleTimes, sampleStates)

#~ write the HIV Model in the canonical (F,G,Y) format
#~ derivative wrt state variable X=c(S, I0, I1)
FofX <- function(X, param)
{
  return(  matrix( rbind(c(X['I0'] * X['S'] * param$beta0, 0), c(X['I1'] * X['S'] * param$beta1, 0)) , 2,2)) 
}
GofX <- function(X, param)
{
  return( matrix( rbind(c(0, X['I0'] * param$gamma0 ), c(0, 0)), 2,2 ) )
}
dX <- function(t, X, param, ...)
{ 
.F <- FofX(X, param)
.G <- GofX(X, param)
list(unname(c(
 -sum(.F) + param$b * X['S'],
 sum(.F) - sum(.G), 
 sum(.G) - param$gamma1 * X['I1']
 )))
}


#~ let's estimate the model parameters beta0 and beta1
#~ this function 1. solves the model 2. defines the Y.,F.,G. globals 3. calculates -log(likelihood)
#~ assume S(0), b, gamma0, gamma1 are known and one initial infection of type I0
#~ NOTE: we estimate the transformed variables log(x) because the rate parameters are confined to (0, Inf)
integrate.model.calculate.minusLogLikelihood <- function(logbeta0, logbeta1)
{
param <- list(beta0 = unname(exp(logbeta0)), beta1 = unname(exp(logbeta1)), gamma0 = gamma0, gamma1=gamma1, b = b)
#~ param <- list(beta0 = unname(exp(theta['logbeta0'])), beta1 = unname(exp(theta['logbeta1'])), gamma0 = gamma0, gamma1=gamma1, b = b)
X0 <-c(S=S0, I0=1, I1=0)
times <- seq(0, 35, length.out = 100)
tryCatch( {o <- ode(X0, times, dX, param)}, error = function(e) { return(Inf) } )
S <- approxfun( o[,1], o[,2] )
Y1 <- approxfun( o[,1], o[,3] )
Y2 <- approxfun( o[,1], o[,4] )
Y. <- function(t) { c(I0 = Y1(t), I1 = Y2(t)) }
F. <- function(t) { FofX(c(S = S(t), Y.(t)), param) }
G. <- function(t) { GofX(c(S = S(t), Y.(t)), param) }
FGY <- list( F. = F., G.=G., Y.=Y. )
browser()
return( -coalescent.log.likelihood(bdt, FGY) )
}


#~ now fit the model
#~ NOTE: this will take a few minutes 
fit <- mle(integrate.model.calculate.minusLogLikelihood, 
	   start = list( logbeta0=log(1.5*beta0),logbeta1=log(beta1/1.5)),
	   method='Nelder-Mead',
	   control=list(maxit=1000 ) )

# now inspect the output
summary(fit)
unname( exp(coef(fit))  )
AIC(fit)
#~ bias
unname( c(beta0,beta1) - exp(coef(fit)) )


#~ approximate 95pc confidence intervals using the mle object
#~ NOTE : more accurate confidence intervals could be found using the profile(fit) function. I recommend using the more robust version of profile in the bbmle package
cis <- unname( rbind( exp( coef(fit) - diag( sqrt( vcov(fit) )) * 1.96 ), 
 exp( coef(fit) + diag( sqrt( vcov(fit) )) * 1.96 ) ) )
 colnames(cis) <- c('beta0', 'beta1')
cis


#~ plot and fitted trajectories to actual trajectories
with(hivSimulationData,  {
plot(t, S, 'l', ylim=c(0, max(S)), col='blue')
lines(t, I0, col='red')
lines(t, I1, col='orange')
})

theta <- coef(fit) 
param <- list(beta0 = unname(exp(theta['logbeta0'])), beta1 = unname(exp(theta['logbeta1'])), gamma0 = gamma0, gamma1=gamma1, b = b)
X0 <-c(S=S0, I0=1, I1=0)
times <- seq(0, 35, length.out = 100)
o <- ode(X0, times, dX, param)
lines(o[,1], o[,2], col='blue')
lines(o[,1], o[,3], col='red')
lines(o[,1], o[,4], col='orange')


#~ save the data
 save( F., G., Y.,  hivSimulationData, bdt, sampleTimes, sampleStates, fit, cis, S0, sampleTime, beta0, beta1, gamma0, gamma1, b, file='HIVModel.RData')


